version: '3'
services:
  inventory_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/inventory_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: db_inventory
    ports:
      - 15432:5432
  inventory:
    build: .
    ports:
      - 9003:9003
    depends_on:
      - inventory_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory_db:5432/db_inventory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 9003
